### ISSUE TITLE
Unable to run "build_my_configs.py" script

### ISSUE THREAD

**Issue by dkoych** [PaloAltoNetworks/iron-skillet#10]
Hi, I am getting the followoing errors when trying to run the script. I tried on different platforms. 
$ python3 ./build_my_configs.py
Traceback (most recent call last):
  File "./build_my_configs.py", line 39, in <module>
    from passlib.hash import des_crypt
ModuleNotFoundError: No module named 'passlib'

[debug.txt](https://github.com/PaloAltoNetworks/iron-skillet/files/2423313/debug.txt)

**Comment by scotchoaf** [comment]
Traveling today and will check the issue when back online. 

Typically use a python virtual env and use pip install -r requirements.txt to install needed packages. Will double check docs to make sure steps are accurate. Same for the requirements file contents. 

Scott

**Comment by scotchoaf** [comment]
Updated the README.md in the tools folder and iron-skillet.readthedocs.io to show how to use the python virtual environment. This is key to simplify installing the requirements.txt packages.

In iron-skillet.readthedocs.io, look in the Creating Loadable Configurations section

**Comment by dkoych** [comment]
Thanks for updating the documentation. It work on my laptop running Cygwin. 
However I get the following error when I try to apply it on Ubuntu Desktop: 

`$ python3.6 -m venv env
Error: Command '['/home/me/iron-skillet/tools/env/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.`

**Comment by scotchoaf** [comment]
Not sure what version of Ubuntu. Older ones only have python3.5 and not 3.6.

Try: python3.5 -m venv env and see if the same error appears. I have modified the iron-skillet tools script to support 3.5 exactly for this issue.
