### ISSUE TITLE
v10.0 branch?

### ISSUE THREAD

**Issue by wegotourselvesareader** [PaloAltoNetworks/iron-skillet#103]
Now that 10.0.0 is out, will iron-skillet be updated to accommodate the new release?

**Comment by stealthllama** [comment]
Yes.  It's in development now.  @scotchoaf can probably give you an idea of timing.

**Comment by scotchoaf** [comment]
should have out the door by end of day tomorrow. Doing final updates with the GA 10.0 release.

If urgent need you can grab my fork with the current updates for 10.0: https://github.com/scotchoaf/iron-skillet/tree/panos_v10.0

**Comment by scotchoaf** [comment]
10.0 branch has been added to github

**Comment by wegotourselvesareader** [comment]
Super, thank you!
