### ISSUE TITLE
"allow-http-range unexpected here"

### ISSUE THREAD

**Issue by SecureYourCloud** [PaloAltoNetworks/iron-skillet#11]
Hi - I generated an iron_skillet config using the tool and when I try to load it to the FW, it complains 

Config loaded from iron_skillet_day1_template.xml
deviceconfig -> setting -> ctd -> allow-http-range unexpected here. Discarding.

Thanks,
Natasha

**Comment by scotchoaf** [comment]
Updating the 8.0 template. Syntax changed between 8.0 and 8.1.

**Comment by scotchoaf** [comment]
Template update and tested. 8.0 xml syntax is:
<skip-block-http-range>no</skip-block-http-range>
