### ISSUE TITLE
Version number discrepancy (v9 / v10) in Panhandler GUI

### ISSUE THREAD

**Issue by wegotourselvesareader** [PaloAltoNetworks/iron-skillet#117]
Panhandler displays "This skillet does a full NGFW validation of IronSkillet day one configuration - panos v10.0" in the initial skillet selection page.

After the assessment is run, Panhandler displays "PAN-OS 9.x" on the results page.

This is with Panhandler version 4.4 2021-05-20T15:24:19, running against a PA-220 with PAN-OS 10.1.0 

Screenshots attached.

- Version used: Version: 4.4 2021-05-20T15:24:19 

![Panhandler](https://user-images.githubusercontent.com/29375176/121649888-e752d980-ca90-11eb-8a0c-dee09f33b852.png)

**Comment by BoraMutluoglu** [comment]
Hello and thanks for this report morrisalex, have you tried to update the IronSkillet repository and PanHandler to the latest versions. I am using PanHandler version: 4.5 2021-06-11T15:53:23, and was not able to re-create this bug. Please try that, run the validation again and let me know if the issue persists. Thank you.

**Comment by BoraMutluoglu** [comment]
Hello morrisalex, if my above advice didn't help then this may be a reporting library issue and I'll get more eyes on it next Monday. Thanks for your patience.

**Comment by wegotourselvesareader** [comment]
By the time I saw your reply, an even newer version had been released - 4.5 2021-06-11T19:29:39

This morning I updated to version 4.5 2021-06-11T19:29:39 and ran the check again. The same visual symptoms exist as shown in the initial screenshots above: one Panhandler page says "10.0", but the next one says "9.x".

**Comment by wegotourselvesareader** [comment]
The same occurs if I update the skillet collection to 10.1 and run the validation check; one page says "10.1",  but the next one still says "9.x".

**Comment by BoraMutluoglu** [comment]
@morrisalex this issue should be fixed with the latest updates to IronSkillet. Please update your repository within PanHandler, run the validation and let me know how it looks for you.

**Comment by wegotourselvesareader** [comment]
I've updated to the latest repository, and it all looks good now. Thanks for fixing this.
