### ISSUE TITLE
Please update Panhandler to add support for PAN-OS 10.1

### ISSUE THREAD

**Issue by wegotourselvesareader** [PaloAltoNetworks/iron-skillet#119]
Please update Panhandler to add support for PAN-OS 10.1.

**Comment by wegotourselvesareader** [comment]
I just noticed a 10.1 branch, which either wasn't there yesterday or I missed it due to being a bit dimwitted. Regardless, it's evident that 10.1 is supported, so I'll close this issue. Thanks.

**Comment by nembery** [comment]
Hi @morrisalex We updated panhandler literally minutes after you opened this, so no worries lol
