### ISSUE TITLE
"Recommended_Decryption_Profile protocol settings max version is TLS 1.3 or max" link takes user to URL Filtering docs, not Decryption docs

### ISSUE THREAD

**Issue by wegotourselvesareader** [PaloAltoNetworks/iron-skillet#123]
## Describe the bug

One of the tests in the "IronSkillet - check NGFW config for updated v10.1 elements" skillet is for the SSL Decryption protocol version.

The text in the test result is a clickable hyperlink which takes the user to some online documentation, but the wrong documentation.

It takes the user to https://iron-skillet.readthedocs.io/en/docs_master/viz_guide_panos.html#url-filtering

It should take the user to https://iron-skillet.readthedocs.io/en/docs_master/viz_guide_panos.html#decryption-profile

- Version used: 4.5 2021-06-11T19:29:39 / the latest 10.1 skillets pulled down at the time of submitting this issue.

![Panhandler_wrong_hyperlink](https://user-images.githubusercontent.com/29375176/121951913-742cba00-cd53-11eb-85f3-1c70075d3e12.png)

**Comment by BoraMutluoglu** [comment]
@morrisalex Hello and thanks for reporting this bug, I will look into fixing this ASAP.

**Comment by BoraMutluoglu** [comment]
@morrisalex Issue should be fixed, updated the documentation link and tested locally. Issue should be fixed after updating the IronSkillet repo in PanHandler. Please let me know if the issue still persists on your side.

**Comment by wegotourselvesareader** [comment]
Updated and tested. Looks good. Thank you.
