### ISSUE TITLE
Superfluous configuration commands in loadable_configs

### ISSUE THREAD

**Issue by wegotourselvesareader** [PaloAltoNetworks/iron-skillet#125]
## Describe the bug

The file iron-skillet-panos_v10.1\loadable_configs\sample-mgmt-dhcp\panos\iron_skillet_panos_full.conf contains some lines (6-12) relating to a static IP configuration.

The file iron-skillet-panos_v10.1\loadable_configs\sample-mgmt-static\panos\iron_skillet_panos_full.conf contains some lines (14-18) relating to a DHCP configuration.

## Expected behavior

The loadable_configs files should contain only commands specific to their intended scenarios.

## Current behavior

The loadable_configs files contain extra commands unrelated to their intended scenarios.

- Version used: 10.1, latest available commit downloaded today

**Comment by BoraMutluoglu** [comment]
Hello morrisalex, thank you for noticing and reporting this. I will take a look at this and report any updates on this issue.

**Comment by BoraMutluoglu** [comment]
Hello morrisalex, we are removing the set commands loadable configs files from all the current loadable config directories. We have opted to place the set commands loadable config .conf file in a completely different directory within the loadable_configs folder. We are going to be allowing the user to use their discretion on whether or not they would like to copy and paste the DHCP or static configurations from the set commands .conf file. Thanks.

**Comment by wegotourselvesareader** [comment]
Thank you for the update. I'll look out for the next release of the Iron Skillet files.

**Comment by scotchoaf** [comment]
I'm going to close this out since we have an update and can open new issues if this isn't fully resolved
