### ISSUE TITLE
Iron-Skillet changed Device Name

### ISSUE THREAD

**Issue by torstenstern** [PaloAltoNetworks/iron-skillet#13]
Hi,

I test right now your iron skillet full xml file for Azure and AWS in Automation Tool (FCA). I figured out that the xml file will override from every Firewall the Device Name to"sample".

`</ntp-servers>
<login-banner>You have accessed a protected system.
Log off immediately if you are not an authorized user.</login-banner>
<timezone>UTC</timezone>
**<hostname>sample</hostname>**
<type>`

[https://github.com/PaloAltoNetworks/iron-skillet/blob/panos_v8.1/loadable_configs/sample-cloud-Azure/panos/iron_skillet_panos_full.xml](url)

Is there really a need that the Iron Skillet is overriding the Device hostname? Then this occurs many issues for us in the FCA tool.

Regards,

Torsten

**Comment by scotchoaf** [comment]
the design is for a full load including all attributes. For cloud deployments can update the full configs to ignore the hostname element

**Comment by scotchoaf** [comment]
not sure if still needed and not other issues related to this problem
