### ISSUE TITLE
Panhandler reports failed check for time zone, with "Etc/UTC"

### ISSUE THREAD

**Issue by wegotourselvesareader** [PaloAltoNetworks/iron-skillet#136]
## Describe the bug

Similar to https://github.com/PaloAltoNetworks/iron-skillet/issues/118 Panhandler appears to be looking for a single specific value for a setting, where more than one value may be appropriate.

Panhandler reports a failure if the firewall's timezone is not "UTC". However, many systems use the recognised standard "Etc/UTC", which is also supported by PAN-OS.

See ftp://ftp.iana.org/tz/data/ for further details on the available timezone names in the tz database

## Expected behavior

Panhandler / Iron Skillet should allow for multiple equivalent values, where appropriate.

## Current behavior

Panhandler / Iron Skillet checks for a single specific value.

## Possible solution

Suggest updating Panhandler / Iron Skillet to accommodate multiple equally-valid options for the time zone.

## Steps to reproduce

1. Set the firewall's timezone to Etc/UTC.
2. Run an Iron Skillet check against the firewall
3. Observe the timezone failure in the report.

## Screenshots

Firewall:
![image](https://user-images.githubusercontent.com/29375176/125376260-8c0f5200-e382-11eb-962c-f243a7e50c32.png)

Panhandler:
![image](https://user-images.githubusercontent.com/29375176/125376350-b103c500-e382-11eb-8a09-d2aa292e7a74.png)

## Your Environment

- Version used: Panhandler 4.5 2021-06-11T19:29:39 // Iron Skillet v10.1 updated 2021-07-06 20:55

**Comment by BoraMutluoglu** [comment]
Hello, I will take a look into this issue and get back to you with updates. Thank you for reporting it.

**Comment by BoraMutluoglu** [comment]
Issue has been fixed. Closing out.

**Comment by wegotourselvesareader** [comment]
Updated the skillet repository inside Panhandler and ran the check again. This time it passes successfully. Many thanks for fixing it.
