### ISSUE TITLE
malformed xml error during the load config partial for panorama version 10.0

### ISSUE THREAD

**Issue by cyberguy001** [PaloAltoNetworks/iron-skillet#142]
## Steps to reproduce

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by BoraMutluoglu** [comment]
Hello and thanks for creating this issue. We have updated IronSkillet 10.0 with bug fixes that should resolve this issue. Please let me know if the issue still persists on your side after working with our most recent changes.

**Comment by cyberguy001** [comment]
Hello,

It's working now, thanks for the quick response.
