### ISSUE TITLE
Custom report no longer created

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#17]
Previously there was a custom report created for potentially compromised machines as well as an email scheduler created.  I'm not seeing those created.  Is that on purpose?

**Comment by scotchoaf** [comment]
there should still be the report along with the email scheduler that is loaded specific to each device group. Updating 9.0 skillet and see if there

**Comment by ctktfg** [comment]
Sorry I'm talking about when iron skillet is applied directly to a firewall - not to Panorama.

**Comment by scotchoaf** [comment]
I see now. I think have to move to 'shared' xpath to show up in the GUI instead of vsys specific. will make the change and update the skillet. from CLI old model there with 'show reports' while in the GUI is 'show shared reports'

**Comment by ctktfg** [comment]
Happy to test when you have a fix.  Just let me know.

**Comment by scotchoaf** [comment]
should be working in 8.1 now. fixing for 8.0 and 9.0 during the day

**Comment by scotchoaf** [comment]
now fixed and locally tested for 8.0, 8.1, 9.0
