### ISSUE TITLE
IPSEC and IKE crypto profiles are unneeded for best practices

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#20]
The BPA tool doesn't call these out as necessary.  Can they be removed from the baseline?  If not, potentially include a variable that allows their exclusion?

**Comment by scotchoaf** [comment]
These are part of the config defaults and will look at impacts of removing from the base config

**Comment by scotchoaf** [comment]
Removed with other elements creating a minimal baseline config
