### ISSUE TITLE
Applications and Threats update config doesn't include a new app threshold

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#23]
The BPA tool wants a value for new app threshold.  Propose adding the following where appropriate:

`<new-app-threshold>12</new-app-threshold>`

**Comment by scotchoaf** [comment]
again, IronSkillet won't be 100% aligned with the BPA. Have to determine impact of widespread deployment so nothing breaks day 1. This may be part of a secondary BPA skillet with additional coverage

**Comment by scotchoaf** [comment]
this may be changed in the BPA. With the new content update model there is less need for the app threshold. Our internal security experts recommended not adding this to IronSkillet
