### ISSUE TITLE
GlobalProtect Data File dynamic update time not specified

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#25]
The BPA tool wants a setting specified for the GP Data File dynamic update time. Propose adding the following where appropriate:

```
            <global-protect-datafile>
              <recurring>
                <hourly>
                  <at>26</at>
                  <action>download-and-install</action>
                </hourly>
              </recurring>
            </global-protect-datafile>
```

**Comment by scotchoaf** [comment]
the team had decided to not make this part of the base template and instead part of a globalprotect configuration option.

**Comment by scotchoaf** [comment]
Will be added using:

NAME: Global Protect / Clientless VPN
PATH: <config urldb="paloaltonetworks" version="VERSION"><devices><entry name="localhost.localdomain"><deviceconfig><system><update-schedule>
XML:
  <global-protect-datafile>
    <recurring>
      <hourly>
        <at>40</at>
        <action>download-and-install</action>
      </hourly>
    </recurring>
  </global-protect-datafile>
  <global-protect-clientless-vpn>
    <recurring>
      <hourly>
        <at>50</at>
        <action>download-and-install</action>
      </hourly>
    </recurring>
  </global-protect-clientless-vpn>

**Comment by scotchoaf** [comment]
Added for all IronSkillet releases
