### ISSUE TITLE
On some platforms Team Cymru IPv6 Bogons list throws warning

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#27]
On some platforms the following error is thrown upon list download:

> Warning: EDL(Team Cymru Bogons IPv6) Exceeded maximum number of ips at line 46960

Just want to put it out there to brainstorm ways around this.  Perhaps don't include the IPv6 in the default block rules?  Open to thoughts...

**Comment by scotchoaf** [comment]
Will have to investigate. We can remove all IPv6 in the next update and create a secondary IPv6 element to use where needed

**Comment by scotchoaf** [comment]
All bogon EDL and associated security rules removed from the current templates
