### ISSUE TITLE
Some URL categories should be blocked for best practices

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#28]
The BPA tool wants to add the following categories as block categories.  Propose adding the following categories to the block list:

copyright-infringement
dynamic-dns
extremism
parked
proxy-avoidance-and-anonymizers
unknown

**Comment by scotchoaf** [comment]
this is the balance with IronSkillet. I'm creating a second stage configuration that is more aggressive. Day 1 blocking of these categories can break non-malicious activity so we have taken 1 step back and many things in the BPA won't show up in the IronSkillet configuration

**Comment by scotchoaf** [comment]
Closing this for now and working on a BPA-focused skillet as add-on to IronSkillet that will include these types of issues that won't be in a generalized day 1
