### ISSUE TITLE
iron_skillet_panos_full.conf says 8.1 when using 9.0 branch

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#34]
When using the panos_v9.0 branch and after running "python3 create_loadable_configs.py", the produced iron_skillet_panos_full.conf says this on line 1:

`# set command configuration for panos version 8.1`

It should say:

`# set command configuration for panos version 9.0`

**Comment by scotchoaf** [comment]
thanks for the note. BTW am currently doing system updates, many of which include this and prior issues. The 90dev and 81dev branches have updated configs.

**Comment by scotchoaf** [comment]
fixed in dev branches and waiting for go live push
