### ISSUE TITLE
Recommended_Zone_Protection snippet is confusing

### ISSUE THREAD

**Issue by panwreaper** [PaloAltoNetworks/iron-skillet#36]
the zone protection snippet is set up like so:
```
<flood>
    <tcp-syn>
      <red>
        <alarm-rate>10000</alarm-rate>
        <activate-rate>10000</activate-rate>
        <maximal-rate>40000</maximal-rate>
      </red>
      <enable>no</enable>
```
since these settings are default (untuned rates and disabled protection) with only a few protections enabled (scanning + spoofing),  I would like to propose renaming the profile to 'NeedsTuning" or "unconfigured', so a novice user does not implement the profile assuming this is Recommended (this snippet is also used in Day1 which is intended for novice users)

**Comment by scotchoaf** [comment]
Will see if can be removed to let the platform set the default or if max values required. These are not part of the initial config snippet and will see if some value required for config to load properly.

**Comment by scotchoaf** [comment]
this is default across platforms and disabled. best we can do is comment in the docs since required as a loadable configuration
