### ISSUE TITLE
Sample loadable configs contain "ip-netmask" instead of "fqdn"

### ISSUE THREAD

**Issue by morrisalex** [PaloAltoNetworks/iron-skillet#55]
If using the provided sample .conf files to apply configuration selectively, the administrator may be tripped up by the sinkhole configuration lines.

These files:
- loadable_configs\sample-cloud-AWS\panos\iron_skillet_panos_full.conf
- loadable_configs\sample-cloud-Azure\panos\iron_skillet_panos_full.conf
- loadable_configs\sample-cloud-GCP\panos\iron_skillet_panos_full.conf
- loadable_configs\sample-mgmt-dhcp\panos\iron_skillet_panos_full.conf
- loadable_configs\sample-mgmt-static\panos\iron_skillet_panos_full.conf

All contain the line:
-  set address Sinkhole-IPv4 ip-netmask sinkhole.paloaltonetworks.com

However (on a PA-220 running 9.0.3-h3 - I don't know if the same occurs on other models and software releases)...
```
# set address Sinkhole-IPv4 ip-netmask sinkhole.paloaltonetworks.com
sinkhole.paloaltonetworks.com is not a valid IPV4/V6 address-netmask.

Invalid syntax.
[edit]
```

Instead...
```
# set address Sinkhole-IPv4 fqdn sinkhole.paloaltonetworks.com

[edit]
```

**Comment by scotchoaf** [comment]
thanks for catching this. Will update with the 'fqdn' config bit in the next release

**Comment by scotchoaf** [comment]
this has been fixed for panos/panorama and all related set/xml elements.
