### ISSUE TITLE
Remove password expiry from password complexity settings

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#68]
Per NIST guidelines (https://pages.nist.gov/800-63-FAQ/#q-b05), expiring passwords are no longer recommended.  I propose setting password expiration to zero in the password complexity settings.  Not sure if it defaults to zero or if you need something like this:

```
<password-complexity>
      <password-change>
        <expiration-period>0</expiration-period>
      </password-change>
</password-complexity>
```

If this change isn't palletable then I propose adding password expiration change warning to the password requirements as right now that is set to zero (I believe by default).  Which means that passwords expire without warning.

**Comment by scotchoaf** [comment]
will add this into consideration for the next review. Agree that is not 0 then the warning should be included

**Comment by scotchoaf** [comment]
agree to remove password expiry. users wanting an expiration can config themselves and see a warning period
