### ISSUE TITLE
Static iron_skillet_panos_full.conf contains "system type dhcp-client" entries

### ISSUE THREAD

**Issue by wegotourselvesareader** [PaloAltoNetworks/iron-skillet#94]
The file iron_skillet_panos_full.conf in the branch https://github.com/PaloAltoNetworks/iron-skillet/tree/panos_v9.1/loadable_configs/sample-mgmt-static/panos contains several configuration commands for a management interface with a dynamic address, not a static address.

See lines 56-59 in that file, which all begin with "set deviceconfig system type dhcp-client"

## Expected behavior

Configuration commands for dynamic management addresses should be in the sample-mgmt-dhcp files, not the sample-mgmt-static files.

## Current behavior

The loadable configs for sample-mgmt-static contain commands related to dynamic management addresses.

## Possible solution

Remove inapplicable commands from scenario-based configuration files, or replace them with scenario-specific commands.

## Your Environment

- Version used: PAN-OS v9.1

**Comment by scotchoaf** [comment]
Will look for a better model here. The dhcp/static is focused on the XML config files where the user can't opt in/out to part of the configurations. The set commands are added as a convenience 'as is' with just the variable var substitutions so both dhcp and static show up.

In the next update will try to include similar dhcp/static logic for the set commands similar to XML

**Comment by scotchoaf** [comment]
I've made a minor update in the panos_9.1 branch. 9.0 updates coming soon. Saw the dhcp client set commands further down in the configuration and moved to the top with the static configuration elements. This will be the extent of logic for the loadable configurations since the Excel sheet also contains both dhcp and static options

**Comment by scotchoaf** [comment]
also fixed for 9.0.
