### ISSUE TITLE
Wildfire size limits don't match best practices

### ISSUE THREAD

**Issue by ctktfg** [PaloAltoNetworks/iron-skillet#95]
Defaults from Iron Skillet for WF sizes don't match best practices

Here's an output from a BPA from a firewall that's a fresh config and has had Iron Skillet applied (including the items that are correct):

Archive File Size Limit (Fail): It is recommended to set the file size limit for "archive" to a value of 50
Flash File Size Limit (Pass)
Jar File Size Limit (Pass)
Linux File Size Limit (Fail): It is recommended to set the file size limit for "linux" to a value of 50
MacOSX File Size Limit (Fail): It is recommended to set the file size limit for "MacOSX" to a value of 10
MS Office File Size Limit (Fail): It is recommended to set the file size limit for "ms-office" to a value of 16384
PDF File Size Limit (Fail): It is recommended to set the file size limit for "pdf" to a value of 3072
PE File Size Limit (Fail): It is recommended to set the file size limit for "pe" to a value of 16
Report Grayware Files Enabled (Pass)
Session Information Settings (Pass)

**Comment by scotchoaf** [comment]
This is a more recent update for 9.x and will include in the next rev of the templates.

**Comment by scotchoaf** [comment]
updated for 9.1 and working on 9.0 updates

**Comment by scotchoaf** [comment]
completed for 9.0 BPA team stated for 9.x so leaving 8.1 as is

**Comment by ctktfg** [comment]
Thanks!
